# Generated by Django 5.0.7 on 2025-03-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_kycverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='id_photo',
            field=models.FileField(upload_to='kyc/id_photos/'),
        ),
    ]
