# Generated by Django 5.0.7 on 2025-03-29 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_alter_kycverification_id_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='activity_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='page_accessed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='referrer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
